url: "https://aigp.org.in"
baseurl: "/"
permalink: pretty
title: "AIGP"
description: "Looking for Indians who are interested in the game of Go, and willing to play this wonderful strategy game. Go, also called baduk, weiqi, or igo is a popular strategy game with a very rich history, still in its infancy in India. Help us get bigger!"

# logo: "assets/images/logo/logo.svg"
logo: "assets/images/logo.png"
site_logo:
  # mobile: "assets/images/logo/logo-mobile.svg"
  mobile: "assets/images/logo.png"
  # mobile_height: "32px"
  mobile_width: "64px"
  # desktop: "assets/images/logo/logo.svg"
  desktop: "assets/images/logo.png"
  # desktop_height: "64px"
  desktop_width: "64px"

collections:
  news:
    output: true
    permalink: /news/:year/:month/:day/:title/

defaults:
  - scope:
      path: "_news"
      type: "news"
    values:
      layout: "news_post"
  - scope:
      path: "_pages"
    values:
      layout: "page"

include:
  - _pages

# Pagination
pagination:
  enabled: true
  collection: 'news'
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  sort_field: 'date'
  sort_reverse: true


sass:
  style: compressed
  quiet_deps: true

plugins:
  - jekyll-environment-variables
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

# reCAPTCHA Configuration
recaptcha_site_key: "6LfIOG4sAAAAAC5WaxUP7j9VAu1-I94xaVrkq1vZ"
